name: Build

on:
  push:
    branches:
      - main
    tags:
      - 1.*

jobs:
  build:
    name: Build App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build (Windows)
      if: ${{ runner.os == 'windows' }}
      run: |
        pyinstaller -wF main.py --icon='image/icon.ico' --add-data 'src/style/style_light.qss;src/style' --add-data 'src/style/table.qss;src/style' --add-data 'src/font/Study-Bold.otf;src/font' --add-data 'image/icon.png;image' --add-data 'image/logo.png;image' --version-file 'version.txt' --name=SubtitleRenamer

    - name: Build (macOS)
      if: ${{ runner.os == 'macos' }}
      run: |
        pyinstaller -wF main.py -i image/icon.icns --add-data src/style:src/style --add-data src/font:src/font --add-data image/logo.png:image --name=SubtitleRenamer

    - name: Build (Linux)
      if: ${{ runner.os == 'linux' }}
      run: |
        pyinstaller -wF main.py --add-data src/style:src/style --add-data src/font:src/font --add-data image/logo.png:image --name=SubtitleRenamer

    - name: Upload (Windows)
      if: ${{ runner.os == 'windows' }}
      uses: actions/upload-artifact@v3
      with:
        name: SubtitleRenamer_windows
        path: |
          dist/*.exe

    - name: Upload (macOS)
      if: ${{ runner.os == 'macos' }}
      uses: actions/upload-artifact@v3
      with:
        name: SubtitleRenamer_mac_x86
        path: |
          dist/*.app

    - name: Upload (Linux)
      if: ${{ runner.os == 'linux' }}
      uses: actions/upload-artifact@v3
      with:
        name: SubtitleRenamer_linux
        path: |
          dist/*
