name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build (Windows)
      if: ${{ runner.os == 'windows' }}
      run: |
        pyinstaller -wF main.py --add-data 'style/style_light.qss;style' --add-data 'style/table.qss;style' --add-data 'image/icon.png;image' --name='SubtitleRenamer'

    - name: Build (macOS)
      if: ${{ runner.os == 'macos' }}
      run: |
        pyinstaller -wF main.py --add-data style:style --name=SubtitleRenamer

    - name: Build (Linux)
      if: ${{ runner.os == 'linux' }}
      run: |
        pyinstaller -wF main.py --add-data style:style --name=SubtitleRenamer

    - name: Upload (Windows)
      if: ${{ runner.os == 'windows' }}
      uses: actions/upload-artifact@v3
      with:
        name: SubtitleRenamer_windows
        path: |
          dist/*.exe

    - name: Upload (macOS)
      if: ${{ runner.os == 'macos' }}
      uses: actions/upload-artifact@v3
      with:
        name: SubtitleRenamer_mac_x86
        path: |
          dist/*.app

    - name: Upload (Linux)
      if: ${{ runner.os == 'linux' }}
      uses: actions/upload-artifact@v3
      with:
        name: SubtitleRenamer_linux
        path: |
          dist/*
